### 데이터 분석 프로세스

#### 데이터 획득, 처리, 시각화 심화

In [7]:
import requests

# 깃허브의 파일 URL
url = 'https://github.com/wikibook/python-for-data-analysis-rev/raw/master/readme.txt'

# URL에 해당하는 파일을 내려받음
r = requests.get(url)

# 파일을 저장할 폴더와 파일명을 지정
file_name = 'C:/myPyCode/data/readme.txt'

# 내려받은 파일을 지정한 폴더에 저장
with open(file_name, 'wb') as f:
    f.write(r.content)

In [8]:
import os

os.path.isfile(file_name) 

True

In [9]:
!type C:\myPyCode\data\missing_data_test.csv

연도,제품1,제품2,제품3,제품4
2015,250,150,,
2016,200,160,170,
2017,150,200,100,150
2018,120,230,130,170
2019,,250,140,


In [10]:
import pandas as pd

data_file = "C:/myPyCode/data/missing_data_test.csv"

df = pd.read_csv(data_file, encoding = "cp949", index_col = "연도")

df

제품1  제품2    제품3    제품4
연도                            
2015  250.0  150    NaN    NaN
2016  200.0  160  170.0    NaN
2017  150.0  200  100.0  150.0
2018  120.0  230  130.0  170.0
2019    NaN  250  140.0    NaN

In [11]:
df.isnull()

제품1    제품2    제품3    제품4
연도                              
2015  False  False   True   True
2016  False  False  False   True
2017  False  False  False  False
2018  False  False  False  False
2019   True  False  False   True

In [12]:
df.isnull().sum()

제품1    1
제품2    0
제품3    1
제품4    3
dtype: int64

In [13]:
df.drop(index=[2019])

제품1  제품2    제품3    제품4
연도                            
2015  250.0  150    NaN    NaN
2016  200.0  160  170.0    NaN
2017  150.0  200  100.0  150.0
2018  120.0  230  130.0  170.0

In [14]:
df.drop(columns=['제품3', '제품4'])

제품1  제품2
연도              
2015  250.0  150
2016  200.0  160
2017  150.0  200
2018  120.0  230
2019    NaN  250

In [15]:
df.drop(index=[2018, 2019], columns=['제품3', '제품4'])

제품1  제품2
연도              
2015  250.0  150
2016  200.0  160
2017  150.0  200

In [16]:
df.dropna() #df.dropna(axis=0)도 결과는 같습니다.

제품1  제품2    제품3    제품4
연도                            
2017  150.0  200  100.0  150.0
2018  120.0  230  130.0  170.0

In [17]:
df.drop(index=[2018, 2019], columns=['제품1', '제품2'])

제품3    제품4
연도                
2015    NaN    NaN
2016  170.0    NaN
2017  100.0  150.0

In [18]:
df.index

Index([2015, 2016, 2017, 2018, 2019], dtype='int64', name='연도')

In [19]:
df.dropna(axis=0, subset=['제품1'])

제품1  제품2    제품3    제품4
연도                            
2015  250.0  150    NaN    NaN
2016  200.0  160  170.0    NaN
2017  150.0  200  100.0  150.0
2018  120.0  230  130.0  170.0

In [20]:
df.dropna(axis=1)

제품2
연도       
2015  150
2016  160
2017  200
2018  230
2019  250

In [21]:
df.dropna(axis=1, subset=[2015])

제품1  제품2
연도              
2015  250.0  150
2016  200.0  160
2017  150.0  200
2018  120.0  230
2019    NaN  250

In [22]:
df.dropna(axis=1, subset=[2016, 2019])

제품2    제품3
연도              
2015  150    NaN
2016  160  170.0
2017  200  100.0
2018  230  130.0
2019  250  140.0

In [23]:
df.loc[2017]

제품1    150.0
제품2    200.0
제품3    100.0
제품4    150.0
Name: 2017, dtype: float64

In [24]:
df.loc[2017].index

Index(['제품1', '제품2', '제품3', '제품4'], dtype='object')

In [25]:
df.loc[2017].values

array([150., 200., 100., 150.])

In [26]:
#평균

In [27]:
avg = (150+200+100+150)/4

In [28]:
avg

150.0

In [38]:
df.describe

<bound method NDFrame.describe of         제품1  제품2    제품3    제품4
연도                            
2015  250.0  150    NaN    NaN
2016  200.0  160  170.0    NaN
2017  150.0  200  100.0  150.0
2018  120.0  230  130.0  170.0
2019    NaN  250  140.0    NaN>

In [29]:
df.제품2

연도
2015    150
2016    160
2017    200
2018    230
2019    250
Name: 제품2, dtype: int64

In [30]:
import numpy as np

In [31]:
np.mean(df.제품2)

198.0

In [32]:
avg=np.mean(df.제품2)

In [33]:
df.제품2.values

array([150, 160, 200, 230, 250], dtype=int64)

In [34]:
#편차(deviation)

In [35]:
deviation=avg-df.제품2.values

In [36]:
deviation

array([ 48.,  38.,  -2., -32., -52.])

In [37]:
deviation**2

array([2304., 1444.,    4., 1024., 2704.])

In [40]:
np.sum(deviation**2)

7480.0

In [41]:
np.sum(deviation**2)/5

1496.0

In [42]:
df.제품2.var

<bound method NDFrame._add_numeric_operations.<locals>.var of 연도
2015    150
2016    160
2017    200
2018    230
2019    250
Name: 제품2, dtype: int64>

In [43]:
np.sqrt(df.제품2.var())

43.243496620879306

In [44]:
np.sum(deviation**2)/5

1496.0

In [45]:
df=df.drop(index=[2019])

In [46]:
df

제품1  제품2    제품3    제품4
연도                            
2015  250.0  150    NaN    NaN
2016  200.0  160  170.0    NaN
2017  150.0  200  100.0  150.0
2018  120.0  230  130.0  170.0

In [47]:
df_copy=df.copy()

In [48]:
df_copy

제품1  제품2    제품3    제품4
연도                            
2015  250.0  150    NaN    NaN
2016  200.0  160  170.0    NaN
2017  150.0  200  100.0  150.0
2018  120.0  230  130.0  170.0

In [49]:
df

제품1  제품2    제품3    제품4
연도                            
2015  250.0  150    NaN    NaN
2016  200.0  160  170.0    NaN
2017  150.0  200  100.0  150.0
2018  120.0  230  130.0  170.0

In [50]:
df = pd.read_csv(data_file, encoding = "cp949", index_col = "연도")

In [51]:
df

제품1  제품2    제품3    제품4
연도                            
2015  250.0  150    NaN    NaN
2016  200.0  160  170.0    NaN
2017  150.0  200  100.0  150.0
2018  120.0  230  130.0  170.0
2019    NaN  250  140.0    NaN

In [52]:
df_copy=df.copy()

In [53]:
df_copy

제품1  제품2    제품3    제품4
연도                            
2015  250.0  150    NaN    NaN
2016  200.0  160  170.0    NaN
2017  150.0  200  100.0  150.0
2018  120.0  230  130.0  170.0
2019    NaN  250  140.0    NaN

In [54]:
df_copy.dropna()

제품1  제품2    제품3    제품4
연도                            
2017  150.0  200  100.0  150.0
2018  120.0  230  130.0  170.0

In [55]:
df_copy2=df.copy()

In [56]:
df_copy2

제품1  제품2    제품3    제품4
연도                            
2015  250.0  150    NaN    NaN
2016  200.0  160  170.0    NaN
2017  150.0  200  100.0  150.0
2018  120.0  230  130.0  170.0
2019    NaN  250  140.0    NaN

In [57]:
df_copy2.dropna(axis=1)

제품2
연도       
2015  150
2016  160
2017  200
2018  230
2019  250

In [58]:
df_copy2_index

NameError: name 'df_copy2_index' is not defined

In [59]:
df_copy2_index

NameError: name 'df_copy2_index' is not defined

In [60]:
df.fillna(0)

제품1  제품2    제품3    제품4
연도                            
2015  250.0  150    0.0    0.0
2016  200.0  160  170.0    0.0
2017  150.0  200  100.0  150.0
2018  120.0  230  130.0  170.0
2019    0.0  250  140.0    0.0

In [61]:
df

제품1  제품2    제품3    제품4
연도                            
2015  250.0  150    NaN    NaN
2016  200.0  160  170.0    NaN
2017  150.0  200  100.0  150.0
2018  120.0  230  130.0  170.0
2019    NaN  250  140.0    NaN

In [62]:
df.fillna(method='bfill')

제품1  제품2    제품3    제품4
연도                            
2015  250.0  150  170.0  150.0
2016  200.0  160  170.0  150.0
2017  150.0  200  100.0  150.0
2018  120.0  230  130.0  170.0
2019    NaN  250  140.0    NaN

In [63]:
df

제품1  제품2    제품3    제품4
연도                            
2015  250.0  150    NaN    NaN
2016  200.0  160  170.0    NaN
2017  150.0  200  100.0  150.0
2018  120.0  230  130.0  170.0
2019    NaN  250  140.0    NaN

In [64]:
df.fillna(method='ffill')

제품1  제품2    제품3    제품4
연도                            
2015  250.0  150    NaN    NaN
2016  200.0  160  170.0    NaN
2017  150.0  200  100.0  150.0
2018  120.0  230  130.0  170.0
2019  120.0  250  140.0  170.0

In [65]:
df

제품1  제품2    제품3    제품4
연도                            
2015  250.0  150    NaN    NaN
2016  200.0  160  170.0    NaN
2017  150.0  200  100.0  150.0
2018  120.0  230  130.0  170.0
2019    NaN  250  140.0    NaN

In [66]:
values = {'제품1': 100,  '제품4': 400}
df.fillna(value=values)

제품1  제품2    제품3    제품4
연도                            
2015  250.0  150    NaN  400.0
2016  200.0  160  170.0  400.0
2017  150.0  200  100.0  150.0
2018  120.0  230  130.0  170.0
2019  100.0  250  140.0  400.0

In [67]:
df

제품1  제품2    제품3    제품4
연도                            
2015  250.0  150    NaN    NaN
2016  200.0  160  170.0    NaN
2017  150.0  200  100.0  150.0
2018  120.0  230  130.0  170.0
2019    NaN  250  140.0    NaN

### 데이터의 요약 및 재구성

#### 데이터의 구조 살펴보기

In [70]:
import pandas as pd

data_file = "C:/myPyCode/data/total_sales_data.csv"

df_sales = pd.read_csv(data_file)
df_sales

매장명  제품종류 모델명  판매  재고
0   A  스마트폰  S1   1   2
1   A  스마트폰  S2   2   5
2   A    TV  V1   3   5
3   B  스마트폰  S2   4   6
4   B  스마트폰  S1   5   8
5   B    TV  V1   6   9
6   C  스마트폰  S2   2   4
7   C    TV  V1   3   6
8   C    TV  V2   7   9

In [71]:
df_sales.columns

Index(['매장명', '제품종류', '모델명', '판매', '재고'], dtype='object')

In [72]:
df_sales.모델명

0    S1
1    S2
2    V1
3    S2
4    S1
5    V1
6    S2
7    V1
8    V2
Name: 모델명, dtype: object

In [73]:
df_sales.describe()

판매        재고
count  9.000000  9.000000
mean   3.666667  6.000000
std    2.000000  2.345208
min    1.000000  2.000000
25%    2.000000  5.000000
50%    3.000000  6.000000
75%    5.000000  8.000000
max    7.000000  9.000000

In [74]:
df_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   매장명     9 non-null      object
 1   제품종류    9 non-null      object
 2   모델명     9 non-null      object
 3   판매      9 non-null      int64 
 4   재고      9 non-null      int64 
dtypes: int64(2), object(3)
memory usage: 492.0+ bytes


In [76]:
df_sales.매장명.value_counts()

매장명
A    3
B    3
C    3
Name: count, dtype: int64

In [77]:
df_sales.pivot_table(index=["매장명", "제품종류", "모델명"],
                     values =["판매","재고"], aggfunc='sum')

재고  판매
매장명 제품종류 모델명        
A   TV   V1    5   3
    스마트폰 S1    2   1
         S2    5   2
B   TV   V1    9   6
    스마트폰 S1    8   5
         S2    6   4
C   TV   V1    6   3
         V2    9   7
    스마트폰 S2    4   2